# .github/workflows/deploy.yml (Corrected for Notebook Deployment)

name: Deploy Databricks Notebooks

# This workflow triggers automatically on any push to the 'main' branch.
on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manual triggering from the GitHub Actions UI

jobs:
  # ====================================================================
  # JOB: Deploy Databricks Notebooks
  # This job syncs your notebooks from Git to the Databricks workspace.
  # ====================================================================
  deploy-databricks-notebooks:
    name: 'Deploy Databricks Notebooks'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository Code
        uses: actions/checkout@v3

      - name: Setup Python for Databricks CLI
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Databricks CLI
        run: pip install databricks-cli

      - name: Configure Databricks CLI Authentication
        run: |
          echo "[DEFAULT]" > ~/.databrickscfg
          echo "host = ${{ secrets.DATABRICKS_HOST }}" >> ~/.databrickscfg
          echo "token = ${{ secrets.DATABRICKS_TOKEN }}" >> ~/.databrickscfg

      - name: Deploy Notebooks to Databricks Workspace
        run: |
          # This command imports the contents of your repo's /notebooks folder
          # into a specific path in the Databricks workspace, overwriting existing files.
          databricks workspace import_dir ./notebooks /Shared/finlake-fraud-detection/ --overwrite